local M = {}

M.highlights_base = function (colors)
  return {
    Normal = { guifg = colors.foreground, guibg = colors.background },
    StatusLineNC = { guibg = colors.background, guifg = colors.background },
    StatusLine = { guibg = colors.background, guifg = colors.background },
    SignColumn = { guibg = colors.background, guifg = colors.background },
    MsgArea = { guifg = colors.foreground, guibg = colors.background },
    ModeMsg = { guifg = colors.foreground, guibg = colors.background },
    MsgSeparator = { guifg = colors.foreground, guibg = colors.background },
    SpellBad = { guifg = colors.color2 },
    SpellCap = { guifg = colors.color6 },
    SpellLocal = { guifg = colors.color4 },
    SpellRare = { guifg = colors.color6 },
    NormalNC = { guifg = colors.foreground, guibg = colors.background },
    Pmenu = { guifg = colors.foreground, guibg = colors.background },
    PmenuSel = { guifg = colors.background, guibg = colors.color4 },
    WildMenu = { guifg = colors.color7, guibg = colors.color4 },
    CursorLineNr = { guifg = colors.cursorline },
    Comment = { guifg = colors.comment },
    Folded = { guifg = colors.color4, guibg = colors.background },
    FoldColumn = { guifg = colors.color4, guibg = colors.background },
    LineNr = { guifg = colors.color0, guibg = colors.background },
    FloatBorder = { guifg = colors.background, guibg = colors.background },
    Whitespace = { guifg = colors.color1 },
    VertSplit = { guifg = colors.background, guibg = colors.color0 },
    CursorLine = { guibg = colors.cursorline },
    CursorColumn = { guibg = colors.background },
    ColorColumn = { guibg = colors.background },
    NormalFloat = { guibg = colors.background },
    Visual = { guibg = colors.color0, guifg = colors.foreground },
    VisualNOS = { guibg = colors.background },
    WarningMsg = { guifg = colors.color3, guibg = colors.background },
    DiffAdd = { guifg = colors.background, guibg = colors.color4 },
    DiffChange = { guifg = colors.background, guibg = colors.color5 },
    DiffDelete = { guifg = colors.background, guibg = colors.color1 },
    QuickFixLine = { guibg = colors.color2 },
    PmenuSbar = { guibg = colors.background },
    PmenuThumb = { guibg = colors.color2 },
    MatchParen = { guifg = colors.color4, guibg = colors.background },
    Cursor = { guifg = colors.fomeground, guibg = colors.cursor },
    lCursor = { guifg = colors.foreground, guibg = colors.cursor },
    CursorIM = { guifg = colors.foreground, guibg = colors.cursor },
    TermCursor = { guifg = colors.foreground, guibg = colors.cursor },
    TermCursorNC = { guifg = colors.foreground, guibg = colors.cursor },
    Conceal = { guifg = colors.color4, guibg = colors.background },
    Directory = { guifg = colors.color4 },
    SpecialKey = { guifg = colors.color4 },
    Title = { guifg = colors.color4 },
    ErrorMsg = { guifg = colors.color1, guibg = colors.background },
    Search = { guifg = colors.background, guibg = colors.color10 },
    IncSearch = { guifg = colors.background, guibg = colors.color10 },
    Substitute = { guifg = colors.color3, guibg = colors.color6 },
    MoreMsg = { guifg = colors.color5 },
    Question = { guifg = colors.color5 },
    EndOfBuffer = { guifg = colors.background },
    NonText = { guifg = colors.color1 },
    Variable = { guifg = colors.color5 },
    String = { guifg = colors.color2 },
    Character = { guifg = colors.color12 },
    Constant = { guifg = colors.color5 },
    Number = { guifg = colors.color3 },
    Boolean = { guifg = colors.color5 },
    Float = { guifg = colors.color5 },
    Identifier = { guifg = colors.color5 },
    Function = { guifg = colors.color6 },
    Operator = { guifg = colors.color6 },
    Type = { guifg = colors.color5 },
    StorageClass = { guifg = colors.color7 },
    Structure = { guifg = colors.color6 },
    Typedef = { guifg = colors.color6 },
    Keyword = { guifg = colors.color6 },
    Statement = { guifg = colors.color6 },
    Conditional = { guifg = colors.color6 },
    Repeat = { guifg = colors.color6 },
    Label = { guifg = colors.color4 },
    Exception = { guifg = colors.color6 },
    Include = { guifg = colors.color6 },
    PreProc = { guifg = colors.color6 },
    Define = { guifg = colors.color6 },
    Macro = { guifg = colors.color6 },
    PreCondit = { guifg = colors.color6 },
    Special = { guifg = colors.color6 },
    SpecialChar = { guifg = colors.foreground },
    Tag = { guifg = colors.color4 },
    Debug = { guifg = colors.color1 },
    Delimiter = { guifg = colors.foreground },
    SpecialComment = { guifg = colors.color2 },
    Ignore = { guifg = colors.color7, guibg = colors.background },
    Todo = { guifg = colors.color1, guibg = colors.background },
    Error = { guifg = colors.color1, guibg = colors.background },
    TabLine = { guifg = colors.color2, guibg = colors.background },
    TabLineSel = { guifg = colors.foreground, guibg = colors.background },
    TabLineFill = { guifg = colors.foreground, guibg = colors.background },
    CmpDocumentationBorder = { guifg = colors.foreground, guibg = colors.background },
    CmpItemAbbr = { guifg = colors.foreground, guibg = colors.background },
    CmpItemAbbrDeprecated = { guifg = colors.color2, guibg = colors.background },
    CmpItemAbbrMatch = { guifg = colors.color7, guibg = colors.background },
    CmpItemAbbrMatchFuzzy = { guifg = colors.color7, guibg = colors.background },
    CmpItemKind = { guifg = colors.color4, guibg = colors.background },
    CmpItemMenu = { guifg = colors.color2, guibg = colors.background },

    -- treesitter
    TSAttribute = { guifg = colors.color4 },
    TSBoolean = { guifg = colors.color6 },
    TSCharacter = { guifg = colors.color4 },
    TSComment = { guifg = colors.comment },
    TSConditional = { guifg = colors.color1 },
    TSConstant = { guifg = colors.color6 },
    TSConstBuiltin = { guifg = colors.color4 },
    TSConstMacro = { guifg = colors.color3 },
    TSConstructor = { guifg = colors.color4 },
    TSException = { guifg = colors.color8 },
    TSField = { guifg = colors.color1 },
    TSFloat = { guifg = colors.color8 },
    TSFunction = { guifg = colors.color1 },
    TSFuncBuiltin = { guifg = colors.color14 },
    TSFuncMacro = { guifg = colors.color2 },
    TSInclude = { guifg = colors.color9 },
    TSKeyword = { guifg = colors.color5 },
    TSKeywordFunction = { guifg = colors.color4 },
    TsKeywordOperator = { guifg = colors.color12 },
    TSKeywordReturn = { guifg = colors.color4 },
    TSLabel = { guifg = colors.color4 },
    TSMethod = { guifg = colors.color12 },
    TSNamespace = { guifg = colors.color9 },
    TSNumber = { guifg = colors.color3 },
    TSParameter = { guifg = colors.color1 },
    TSParameterReference = { guifg = colors.color9 },
    TSProperty = { guifg = colors.color1 },
    TSPunctDelimiter = { guifg = colors.color7 },
    TSPunctBracket = { guifg = colors.color7 },
    TSPunctSpecial = { guifg = colors.color7 },
    TSRepeat = { guifg = colors.color11 },
    TSString = { guifg = colors.color2 },
    TSStringRegex = { guifg = colors.color2 },
    TSStringEscape = { guifg = colors.color4 },
    TSStringSpecial = { guifg = colors.color4 },
    TSSymbol = { guifg = colors.color1 },
    TSTag = { guifg = colors.color4 },
    TSTagAttribute = { guifg = colors.color1 },
    TSTagDelimiter = { guifg = colors.color7 },
    TSText = { guifg = colors.color7 },
    TSStrong = { guifg = colors.color7 },
    TSEmphasis = { guifg = colors.color7 }, -- italic
    TSUnderline = { guifg = colors.color5 },
    TSStrike = { guifg = colors.color7 },
    TSTitle = { guifg = colors.color3 },
    TSLiteral = { guifg = colors.color2 },
    TSURI = { guifg = colors.color3 },
    TSMath = { guifg = colors.color6 },
    TSTextReference = { guifg = colors.color6 },
    TSEnvirontment = { guifg = colors.color5 },
    TSEnvironmentName = { guifg = colors.color3 },
    TSNote = { guifg = colors.color8 },
    TSWarning = { guifg = colors.color0, guibg = colors.color1 },
    TSDanger = { guifg = colors.color8 },
    TSType = { guifg = colors.color3 },
    TSTypeBuiltin = { guifg = colors.color3 },
    TSVariable = { guifg = colors.color7 },
    TSVariableBuiltin = { guifg = colors.color4 },

    -- LspTrouble
    LspTroubleText = { guifg = colors.foreground },
    LspTroubleCount = { guifg = colors.color6, guibg = colors.foreground },
    LspTroubleNormal = { guifg = colors.foreground, guibg = colors.background },

    -- Illuminate
    illuminatedWord = { guibg = colors.foreground },
    illuminatedCurWord = { guibg = colors.foreground },

    -- diff
    diffAdded = { guifg = colors.color4 },
    diffRemoved = { guifg = colors.color1 },
    diffChanged = { guifg = colors.color5 },
    diffOldFile = { guifg = colors.color5 },
    diffNewFile = { guifg = colors.color5 },
    diffFile = { guifg = colors.color7 },
    diffLine = { guifg = colors.color1 },
    diffIndexLine = { guifg = colors.color6 },

   -- Neogit
    NeogitBranch = { guifg = colors.color6 },
    NeogitRemote = { guifg = colors.color6 },
    NeogitHunkHeader = { guibg = colors.background, guifg = colors.foreground },
    NeogitHunkHeaderHighlight = { guibg = colors.foreground, guifg = colors.color7 },
    NeogitDiffContextHighlight = { guibg = colors.background, guifg = colors.foreground },
    NeogitDiffDeleteHighlight = { guifg = colors.color1, guibg = colors.color1 },
    NeogitDiffAddHighlight = { guifg = colors.color4, guibg = colors.color4 },

    -- GitGutter
    GitGutterAdd = { guifg = colors.color4 }, -- diff mode: Added line |diff.txt|
    GitGutterChange = { guifg = colors.color5 }, -- diff mode: Changed line |diff.txt|
    GitGutterDelete = { guifg = colors.color1 }, -- diff mode: Deleted line |diff.txt|

    -- GitSigns
    GitSignsAdd = { guifg = colors.color4 }, -- diff mode: Added line |diff.txt|
    GitSignsChange = { guifg = colors.color5 }, -- diff mode: Changed line |diff.txt|
    GitSignsDelete = { guifg = colors.color1 }, -- diff mode: Deleted line |diff.txt|

    -- Telescope
    TelescopeBorder = { guifg = colors.color0, guibg = colors.background },
    TelescopeNormal = { guifg = colors.foreground, guibg = colors.background },
    TelescopeSelection = { guifg = colors.background, guibg = colors.color2 },

    -- Indent Blank Line
    IndentBlanklineChar = { guifg = colors.color0, guibg = colors.background },

    -- NvimTree
    NvimTreeNormal = { guifg = colors.foreground, guibg = colors.background },
    NvimTreeNormalNC = { guifg = colors.foreground, guibg = colors.background },
    NvimTreeRootFolder = { guifg = colors.color1 },
    NvimTreeGitDirty = { guifg = colors.color5 },
    NvimTreeGitNew = { guifg = colors.color4 },
    NvimTreeGitDeleted = { guifg = colors.color1 },
    NvimTreeSpecialFile = { guifg = colors.color6 },
    NvimTreeIndentMarker = { guifg = colors.color0 },
    NvimTreeImageFile = { guifg = colors.foreground },
    NvimTreeSymlink = { guifg = colors.color7 },
    NvimTreeFolderIcon = { guifg = colors.color4, guibg = colors.background },
    NvimTreeFolderName = { guifg = colors.foreground },
    NvimTreeOpenedFolderName = { guifg = colors.color2 },
    NvimTreeEmptyFolderName = { guifg = colors.color2 },
    NvimTreeStatusLineNC = { guibg = colors.background, guifg = colors.background },

    -- LspSaga
    LspFloatWinNormal = { guibg = colors.background },
    LspFloatWinBorder = { guifg = colors.background },
    LspSagaBorderTitle = { guifg = colors.color7 },
    LspSagaHoverBorder = { guifg = colors.color7 },
    LspSagaRenameBorder = { guifg = colors.color4 },
    LspSagaDefPreviewBorder = { guifg = colors.color4 },
    LspSagaCodeActionBorder = { guifg = colors.color7 },
    LspSagaFinderSelection = { guifg = colors.color1 },
    LspSagaCodeActionTitle = { guifg = colors.color7 },
    LspSagaCodeActionContent = { guifg = colors.color6 },
    LspSagaSignatureHelpBorder = { guifg = colors.color1 },
    ReferencesCount = { guifg = colors.color6 },
    DefinitionCount = { guifg = colors.color6 },
    DefinitionIcon = { guifg = colors.color7 },
    ReferencesIcon = { guifg = colors.color7 },
    TargetWord = { guifg = colors.color7 },

    -- NeoVim
    healthError = { guifg = colors.color1 },
    healthSuccess = { guifg = colors.color4 },
    healthWarning = { guifg = colors.color5 },

    -- BufferLine
    BufferLineIndicatorSelected = { guifg = colors.color2 },
    BufferLineFill = { guifg = colors.background, guibg = colors.background },
  }
end

return M
